// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { BucketApiCreateBucketData, BucketApiCreateBucketResponses, BucketApiDeleteBucketData, BucketApiDeleteBucketResponses, BucketApiGetBucketData, BucketApiGetBucketResponses, BucketApiListBucketsData, BucketApiListBucketsResponses, BucketApiUpdateBucketData, BucketApiUpdateBucketResponses, DocumentsApiCreateDocumentData, DocumentsApiCreateDocumentResponses, DocumentsApiDeleteDocumentData, DocumentsApiDeleteDocumentResponses, DocumentsApiGetDoclingSettingsData, DocumentsApiGetDoclingSettingsResponses, DocumentsApiGetDocumentData, DocumentsApiGetDocumentProgressData, DocumentsApiGetDocumentProgressResponses, DocumentsApiGetDocumentResponses, DocumentsApiGetImageData, DocumentsApiGetImageResponses, DocumentsApiGetPageData, DocumentsApiGetPageImagesData, DocumentsApiGetPageImagesResponses, DocumentsApiGetPageResponses, DocumentsApiListDocumentsData, DocumentsApiListDocumentsResponses, DocumentsApiListPagesData, DocumentsApiListPagesResponses, DocumentsApiSearchPagesData, DocumentsApiSearchPagesResponses, DocumentsApiUpdateDoclingSettingsData, DocumentsApiUpdateDoclingSettingsResponses, DocumentsApiUpdateDocumentData, DocumentsApiUpdateDocumentResponses, DocumentsApiUpdatePageData, DocumentsApiUpdatePageResponses, DocumentsApiUploadDocumentData, DocumentsApiUploadDocumentResponses, PagewiseApiHealthCheckData, PagewiseApiHealthCheckResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 */
export const pagewiseApiHealthCheck = <ThrowOnError extends boolean = false>(options?: Options<PagewiseApiHealthCheckData, ThrowOnError>) => (options?.client ?? client).get<PagewiseApiHealthCheckResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * List Buckets
 *
 * Get all buckets
 */
export const bucketApiListBuckets = <ThrowOnError extends boolean = false>(options?: Options<BucketApiListBucketsData, ThrowOnError>) => (options?.client ?? client).get<BucketApiListBucketsResponses, unknown, ThrowOnError>({ url: '/api/buckets/', ...options });

/**
 * Create Bucket
 *
 * Create a new bucket
 */
export const bucketApiCreateBucket = <ThrowOnError extends boolean = false>(options: Options<BucketApiCreateBucketData, ThrowOnError>) => (options.client ?? client).post<BucketApiCreateBucketResponses, unknown, ThrowOnError>({
    url: '/api/buckets/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Bucket
 *
 * Delete a bucket
 */
export const bucketApiDeleteBucket = <ThrowOnError extends boolean = false>(options: Options<BucketApiDeleteBucketData, ThrowOnError>) => (options.client ?? client).delete<BucketApiDeleteBucketResponses, unknown, ThrowOnError>({ url: '/api/buckets/{sqid}', ...options });

/**
 * Get Bucket
 *
 * Get a specific bucket by sqid
 */
export const bucketApiGetBucket = <ThrowOnError extends boolean = false>(options: Options<BucketApiGetBucketData, ThrowOnError>) => (options.client ?? client).get<BucketApiGetBucketResponses, unknown, ThrowOnError>({ url: '/api/buckets/{sqid}', ...options });

/**
 * Update Bucket
 *
 * Update a bucket
 */
export const bucketApiUpdateBucket = <ThrowOnError extends boolean = false>(options: Options<BucketApiUpdateBucketData, ThrowOnError>) => (options.client ?? client).put<BucketApiUpdateBucketResponses, unknown, ThrowOnError>({
    url: '/api/buckets/{sqid}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Documents
 *
 * Get all documents, optionally filtered by bucket
 */
export const documentsApiListDocuments = <ThrowOnError extends boolean = false>(options?: Options<DocumentsApiListDocumentsData, ThrowOnError>) => (options?.client ?? client).get<DocumentsApiListDocumentsResponses, unknown, ThrowOnError>({ url: '/api/documents/', ...options });

/**
 * Create Document
 *
 * Create a new document
 */
export const documentsApiCreateDocument = <ThrowOnError extends boolean = false>(options: Options<DocumentsApiCreateDocumentData, ThrowOnError>) => (options.client ?? client).post<DocumentsApiCreateDocumentResponses, unknown, ThrowOnError>({
    url: '/api/documents/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Upload Document
 *
 * Upload a PDF document and start processing
 */
export const documentsApiUploadDocument = <ThrowOnError extends boolean = false>(options: Options<DocumentsApiUploadDocumentData, ThrowOnError>) => (options.client ?? client).post<DocumentsApiUploadDocumentResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/documents/upload/',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete Document
 *
 * Delete a document
 */
export const documentsApiDeleteDocument = <ThrowOnError extends boolean = false>(options: Options<DocumentsApiDeleteDocumentData, ThrowOnError>) => (options.client ?? client).delete<DocumentsApiDeleteDocumentResponses, unknown, ThrowOnError>({ url: '/api/documents/{sqid}', ...options });

/**
 * Get Document
 *
 * Get a specific document by sqid
 */
export const documentsApiGetDocument = <ThrowOnError extends boolean = false>(options: Options<DocumentsApiGetDocumentData, ThrowOnError>) => (options.client ?? client).get<DocumentsApiGetDocumentResponses, unknown, ThrowOnError>({ url: '/api/documents/{sqid}', ...options });

/**
 * Update Document
 *
 * Update a document
 */
export const documentsApiUpdateDocument = <ThrowOnError extends boolean = false>(options: Options<DocumentsApiUpdateDocumentData, ThrowOnError>) => (options.client ?? client).put<DocumentsApiUpdateDocumentResponses, unknown, ThrowOnError>({
    url: '/api/documents/{sqid}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Document Progress
 *
 * Get document processing progress
 */
export const documentsApiGetDocumentProgress = <ThrowOnError extends boolean = false>(options: Options<DocumentsApiGetDocumentProgressData, ThrowOnError>) => (options.client ?? client).get<DocumentsApiGetDocumentProgressResponses, unknown, ThrowOnError>({ url: '/api/documents/{sqid}/progress', ...options });

/**
 * List Pages
 *
 * Get all pages, optionally filtered by document
 */
export const documentsApiListPages = <ThrowOnError extends boolean = false>(options?: Options<DocumentsApiListPagesData, ThrowOnError>) => (options?.client ?? client).get<DocumentsApiListPagesResponses, unknown, ThrowOnError>({ url: '/api/pages/', ...options });

/**
 * Get Page
 *
 * Get a specific page by sqid
 */
export const documentsApiGetPage = <ThrowOnError extends boolean = false>(options: Options<DocumentsApiGetPageData, ThrowOnError>) => (options.client ?? client).get<DocumentsApiGetPageResponses, unknown, ThrowOnError>({ url: '/api/pages/{sqid}', ...options });

/**
 * Update Page
 *
 * Update a page
 */
export const documentsApiUpdatePage = <ThrowOnError extends boolean = false>(options: Options<DocumentsApiUpdatePageData, ThrowOnError>) => (options.client ?? client).put<DocumentsApiUpdatePageResponses, unknown, ThrowOnError>({
    url: '/api/pages/{sqid}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Page Images
 *
 * Get all images from a specific page
 */
export const documentsApiGetPageImages = <ThrowOnError extends boolean = false>(options: Options<DocumentsApiGetPageImagesData, ThrowOnError>) => (options.client ?? client).get<DocumentsApiGetPageImagesResponses, unknown, ThrowOnError>({ url: '/api/pages/{sqid}/images/', ...options });

/**
 * Get Image
 *
 * Get a specific image by sqid
 */
export const documentsApiGetImage = <ThrowOnError extends boolean = false>(options: Options<DocumentsApiGetImageData, ThrowOnError>) => (options.client ?? client).get<DocumentsApiGetImageResponses, unknown, ThrowOnError>({ url: '/api/images/{sqid}', ...options });

/**
 * Search Pages
 *
 * Search pages using PostgreSQL text matching and similarity
 */
export const documentsApiSearchPages = <ThrowOnError extends boolean = false>(options?: Options<DocumentsApiSearchPagesData, ThrowOnError>) => (options?.client ?? client).get<DocumentsApiSearchPagesResponses, unknown, ThrowOnError>({ url: '/api/search/', ...options });

/**
 * Get Docling Settings
 *
 * Get current Docling settings
 */
export const documentsApiGetDoclingSettings = <ThrowOnError extends boolean = false>(options?: Options<DocumentsApiGetDoclingSettingsData, ThrowOnError>) => (options?.client ?? client).get<DocumentsApiGetDoclingSettingsResponses, unknown, ThrowOnError>({ url: '/api/settings/', ...options });

/**
 * Update Docling Settings
 *
 * Update Docling settings
 */
export const documentsApiUpdateDoclingSettings = <ThrowOnError extends boolean = false>(options: Options<DocumentsApiUpdateDoclingSettingsData, ThrowOnError>) => (options.client ?? client).put<DocumentsApiUpdateDoclingSettingsResponses, unknown, ThrowOnError>({
    url: '/api/settings/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
