// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * PondSchema
 */
export type PondSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PondCreateSchema
 */
export type PondCreateSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * PondUpdateSchema
 */
export type PondUpdateSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * PondShareSchema
 */
export type PondShareSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Pond Sqid
     */
    pond_sqid: string;
    /**
     * Expire Date
     */
    expire_date: string;
    /**
     * Access Count
     */
    access_count: number;
    /**
     * Is Expired
     */
    is_expired: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PondShareCreateSchema
 */
export type PondShareCreateSchema = {
    /**
     * Pond Sqid
     */
    pond_sqid: string;
    /**
     * Expire Date
     *
     * Expiration date for the share link
     */
    expire_date: string;
};

/**
 * PublicPondSchema
 *
 * Schema for publicly shared pond data
 */
export type PublicPondSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * DocumentListFilterSchema
 */
export type DocumentListFilterSchema = {
    /**
     * Processing Status
     */
    processing_status?: string | null;
};

/**
 * Input
 */
export type Input = {
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
};

/**
 * DocumentSchema
 */
export type DocumentSchema = {
    /**
     * Processing Progress
     */
    processing_progress: number;
    /**
     * Pages
     */
    pages: Array<PageSchema>;
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Title
     */
    title: string;
    /**
     * Thumbnail
     */
    thumbnail?: string | null;
    /**
     * Page Count
     */
    page_count?: number;
    /**
     * Original Pdf
     */
    original_pdf: string;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PageSchema
 */
export type PageSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Page Number
     */
    page_number: number;
};

/**
 * PagedDocumentSchema
 */
export type PagedDocumentSchema = {
    /**
     * Items
     */
    items: Array<DocumentSchema>;
    /**
     * Count
     */
    count: number;
};

/**
 * DocumentCreateSchema
 */
export type DocumentCreateSchema = {
    /**
     * Title
     */
    title: string;
    /**
     * Pond Sqid
     */
    pond_sqid: string;
    /**
     * Docling Preset Sqid
     */
    docling_preset_sqid?: string | null;
    /**
     * Ocr Preset Sqid
     */
    ocr_preset_sqid?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * DocumentUpdateSchema
 */
export type DocumentUpdateSchema = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Docling Preset Sqid
     */
    docling_preset_sqid?: string | null;
    /**
     * Ocr Preset Sqid
     */
    ocr_preset_sqid?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * PagesListFilterSchema
 */
export type PagesListFilterSchema = {
    /**
     * Document Id
     */
    document_id?: string | null;
};

/**
 * PagedPageSchema
 */
export type PagedPageSchema = {
    /**
     * Items
     */
    items: Array<PageSchema>;
    /**
     * Count
     */
    count: number;
};

/**
 * PageDetailsSchema
 */
export type PageDetailsSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Page Number
     */
    page_number: number;
    /**
     * Page Pdf
     */
    page_pdf: string;
    /**
     * Page Image
     *
     * Preview image of the page
     */
    page_image?: string | null;
    /**
     * Ocr Markdown Raw
     */
    ocr_markdown_raw?: string | null;
    /**
     * Docling Json
     *
     * Original docling JSON output
     */
    docling_json?: {
        [key: string]: unknown;
    } | null;
    /**
     * Docling Json Override
     *
     * Corrected/overridden docling JSON data
     */
    docling_json_override?: {
        [key: string]: unknown;
    } | null;
    /**
     * Text Markdown Clean
     */
    text_markdown_clean?: string | null;
    /**
     * Processing Status
     */
    processing_status?: string;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PageUpdateSchema
 */
export type PageUpdateSchema = {
    /**
     * Ocr Markdown Raw
     */
    ocr_markdown_raw?: string | null;
    /**
     * Text Markdown Clean
     */
    text_markdown_clean?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ImageSchema
 */
export type ImageSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Image File
     */
    image_file: string;
    /**
     * Caption
     */
    caption?: string | null;
    /**
     * Metadata
     */
    metadata: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * SearchFilterSchema
 */
export type SearchFilterSchema = {
    /**
     * Q
     */
    q?: string | null;
    /**
     * Min Score
     */
    min_score?: number | null;
    /**
     * Document Title
     */
    document_title?: string | null;
    /**
     * Pond Name
     */
    pond_name?: string | null;
};

/**
 * SearchDocumentSchema
 */
export type SearchDocumentSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Title
     */
    title: string;
    /**
     * Thumbnail
     */
    thumbnail?: string | null;
    /**
     * Pages
     */
    pages: Array<SearchPageSchema>;
    /**
     * Max Relevance Score
     */
    max_relevance_score: number;
};

/**
 * SearchPageSchema
 */
export type SearchPageSchema = {
    /**
     * Snippet
     */
    snippet?: string | null;
    /**
     * Relevance Score
     */
    relevance_score?: number | null;
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Page Number
     */
    page_number: number;
    /**
     * Text Markdown Clean
     */
    text_markdown_clean?: string | null;
    /**
     * Processing Status
     */
    processing_status?: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * SearchResultSchema
 */
export type SearchResultSchema = {
    /**
     * Documents
     */
    documents: Array<SearchDocumentSchema>;
    /**
     * Total Results
     */
    total_results: number;
};

/**
 * OcrPresetSchema
 */
export type OcrPresetSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * Force Ocr
     */
    force_ocr: boolean;
    /**
     * Skip Text
     */
    skip_text: boolean;
    /**
     * Redo Ocr
     */
    redo_ocr: boolean;
    /**
     * Ocr Backend
     */
    ocr_backend: string;
    /**
     * Language
     */
    language: string;
    /**
     * Optimize
     */
    optimize: number;
    /**
     * Jpeg Quality
     */
    jpeg_quality: number;
    /**
     * Png Quality
     */
    png_quality: number;
    /**
     * Deskew
     */
    deskew: boolean;
    /**
     * Do Clean
     */
    do_clean: boolean;
    /**
     * Do Clean Final
     */
    do_clean_final: boolean;
    /**
     * Remove Background
     */
    remove_background: boolean;
    /**
     * Oversample
     */
    oversample: number;
    /**
     * Rotate Pages
     */
    rotate_pages: boolean;
    /**
     * Remove Vectors
     */
    remove_vectors: boolean;
    /**
     * Advanced Settings
     */
    advanced_settings: {
        [key: string]: unknown;
    };
};

/**
 * OcrPresetCreateSchema
 */
export type OcrPresetCreateSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Is Default
     */
    is_default?: boolean;
    /**
     * Force Ocr
     */
    force_ocr?: boolean;
    /**
     * Skip Text
     */
    skip_text?: boolean;
    /**
     * Redo Ocr
     */
    redo_ocr?: boolean;
    /**
     * Ocr Backend
     */
    ocr_backend?: string;
    /**
     * Language
     */
    language?: string;
    /**
     * Optimize
     */
    optimize?: number;
    /**
     * Jpeg Quality
     */
    jpeg_quality?: number;
    /**
     * Png Quality
     */
    png_quality?: number;
    /**
     * Deskew
     */
    deskew?: boolean;
    /**
     * Do Clean
     */
    do_clean?: boolean;
    /**
     * Do Clean Final
     */
    do_clean_final?: boolean;
    /**
     * Remove Background
     */
    remove_background?: boolean;
    /**
     * Oversample
     */
    oversample?: number;
    /**
     * Rotate Pages
     */
    rotate_pages?: boolean;
    /**
     * Remove Vectors
     */
    remove_vectors?: boolean;
    /**
     * Advanced Settings
     */
    advanced_settings?: {
        [key: string]: unknown;
    };
};

/**
 * OcrPresetUpdateSchema
 */
export type OcrPresetUpdateSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Is Default
     */
    is_default?: boolean | null;
    /**
     * Force Ocr
     */
    force_ocr?: boolean | null;
    /**
     * Skip Text
     */
    skip_text?: boolean | null;
    /**
     * Redo Ocr
     */
    redo_ocr?: boolean | null;
    /**
     * Ocr Backend
     */
    ocr_backend?: string | null;
    /**
     * Language
     */
    language?: string | null;
    /**
     * Optimize
     */
    optimize?: number | null;
    /**
     * Jpeg Quality
     */
    jpeg_quality?: number | null;
    /**
     * Png Quality
     */
    png_quality?: number | null;
    /**
     * Deskew
     */
    deskew?: boolean | null;
    /**
     * Do Clean
     */
    do_clean?: boolean | null;
    /**
     * Do Clean Final
     */
    do_clean_final?: boolean | null;
    /**
     * Remove Background
     */
    remove_background?: boolean | null;
    /**
     * Oversample
     */
    oversample?: number | null;
    /**
     * Rotate Pages
     */
    rotate_pages?: boolean | null;
    /**
     * Remove Vectors
     */
    remove_vectors?: boolean | null;
    /**
     * Advanced Settings
     */
    advanced_settings?: {
        [key: string]: unknown;
    } | null;
};

/**
 * DoclingPresetSchema
 */
export type DoclingPresetSchema = {
    [key: string]: unknown;
};

/**
 * PagedDoclingPresetSchema
 */
export type PagedDoclingPresetSchema = {
    /**
     * Items
     */
    items: Array<DoclingPresetSchema>;
    /**
     * Count
     */
    count: number;
};

/**
 * DoclingPresetCreateSchema
 */
export type DoclingPresetCreateSchema = {
    /**
     * Name
     *
     * Preset name
     */
    name: string;
    /**
     * Is Default
     *
     * Set as default preset
     */
    is_default?: boolean;
    /**
     * Pipeline Type
     *
     * Pipeline type: standard PDF or VLM
     */
    pipeline_type?: string;
    /**
     * Ocr Engine
     *
     * OCR engine to use
     */
    ocr_engine?: string;
    /**
     * Force Ocr
     *
     * Force full page OCR even for PDFs with text
     */
    force_ocr?: boolean;
    /**
     * Ocr Languages
     *
     * List of language codes for OCR (format depends on OCR engine)
     */
    ocr_languages?: {
        [key: string]: unknown;
    } | null;
    /**
     * Vlm Model
     *
     * VLM model repo ID (e.g., 'ibm-granite/granite-docling-258M')
     */
    vlm_model?: string | null;
    /**
     * Enable Picture Description
     *
     * Generate descriptions for images using VLM
     */
    enable_picture_description?: boolean;
    /**
     * Picture Description Prompt
     *
     * Prompt for picture description model
     */
    picture_description_prompt?: string | null;
    /**
     * Enable Table Structure
     *
     * Enable table structure extraction
     */
    enable_table_structure?: boolean;
    /**
     * Table Former Mode
     *
     * TableFormer extraction mode
     */
    table_former_mode?: string;
    /**
     * Enable Code Enrichment
     *
     * Enable specialized processing for code blocks
     */
    enable_code_enrichment?: boolean;
    /**
     * Enable Formula Enrichment
     *
     * Enable LaTeX formula recognition
     */
    enable_formula_enrichment?: boolean;
    /**
     * Filter Orphan Clusters
     *
     * Filter out orphaned text clusters (e.g., page numbers, headers)
     */
    filter_orphan_clusters?: boolean;
    /**
     * Filter Empty Clusters
     *
     * Filter out empty clusters in layout
     */
    filter_empty_clusters?: boolean;
    /**
     * Advanced Settings
     *
     * Advanced pipeline options in JSON format
     */
    advanced_settings?: {
        [key: string]: unknown;
    } | null;
};

/**
 * DoclingPresetUpdateSchema
 */
export type DoclingPresetUpdateSchema = {
    /**
     * Name
     *
     * Preset name
     */
    name: string;
    /**
     * Is Default
     *
     * Set as default preset
     */
    is_default?: boolean;
    /**
     * Pipeline Type
     *
     * Pipeline type: standard PDF or VLM
     */
    pipeline_type?: string;
    /**
     * Ocr Engine
     *
     * OCR engine to use
     */
    ocr_engine?: string;
    /**
     * Force Ocr
     *
     * Force full page OCR even for PDFs with text
     */
    force_ocr?: boolean;
    /**
     * Ocr Languages
     *
     * List of language codes for OCR (format depends on OCR engine)
     */
    ocr_languages?: {
        [key: string]: unknown;
    } | null;
    /**
     * Vlm Model
     *
     * VLM model repo ID (e.g., 'ibm-granite/granite-docling-258M')
     */
    vlm_model?: string | null;
    /**
     * Enable Picture Description
     *
     * Generate descriptions for images using VLM
     */
    enable_picture_description?: boolean;
    /**
     * Picture Description Prompt
     *
     * Prompt for picture description model
     */
    picture_description_prompt?: string | null;
    /**
     * Enable Table Structure
     *
     * Enable table structure extraction
     */
    enable_table_structure?: boolean;
    /**
     * Table Former Mode
     *
     * TableFormer extraction mode
     */
    table_former_mode?: string;
    /**
     * Enable Code Enrichment
     *
     * Enable specialized processing for code blocks
     */
    enable_code_enrichment?: boolean;
    /**
     * Enable Formula Enrichment
     *
     * Enable LaTeX formula recognition
     */
    enable_formula_enrichment?: boolean;
    /**
     * Filter Orphan Clusters
     *
     * Filter out orphaned text clusters (e.g., page numbers, headers)
     */
    filter_orphan_clusters?: boolean;
    /**
     * Filter Empty Clusters
     *
     * Filter out empty clusters in layout
     */
    filter_empty_clusters?: boolean;
    /**
     * Advanced Settings
     *
     * Advanced pipeline options in JSON format
     */
    advanced_settings?: {
        [key: string]: unknown;
    } | null;
};

export type DocpondApiHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type DocpondApiHealthCheckResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PondsApiListPondsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ponds/';
};

export type PondsApiListPondsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<PondSchema>;
};

export type PondsApiListPondsResponse = PondsApiListPondsResponses[keyof PondsApiListPondsResponses];

export type PondsApiCreatePondData = {
    body: PondCreateSchema;
    path?: never;
    query?: never;
    url: '/api/ponds/';
};

export type PondsApiCreatePondResponses = {
    /**
     * OK
     */
    200: PondSchema;
};

export type PondsApiCreatePondResponse = PondsApiCreatePondResponses[keyof PondsApiCreatePondResponses];

export type PondsApiDeletePondData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/ponds/{sqid}';
};

export type PondsApiDeletePondResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PondsApiGetPondData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/ponds/{sqid}';
};

export type PondsApiGetPondResponses = {
    /**
     * OK
     */
    200: PondSchema;
};

export type PondsApiGetPondResponse = PondsApiGetPondResponses[keyof PondsApiGetPondResponses];

export type PondsApiUpdatePondData = {
    body: PondUpdateSchema;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/ponds/{sqid}';
};

export type PondsApiUpdatePondResponses = {
    /**
     * OK
     */
    200: PondSchema;
};

export type PondsApiUpdatePondResponse = PondsApiUpdatePondResponses[keyof PondsApiUpdatePondResponses];

export type PondsApiListPondSharesData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/ponds/{sqid}/shares';
};

export type PondsApiListPondSharesResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<PondShareSchema>;
};

export type PondsApiListPondSharesResponse = PondsApiListPondSharesResponses[keyof PondsApiListPondSharesResponses];

export type PondsApiCreatePondShareData = {
    body: PondShareCreateSchema;
    path?: never;
    query?: never;
    url: '/api/ponds/shares';
};

export type PondsApiCreatePondShareResponses = {
    /**
     * OK
     */
    200: PondShareSchema;
};

export type PondsApiCreatePondShareResponse = PondsApiCreatePondShareResponses[keyof PondsApiCreatePondShareResponses];

export type PondsApiDeletePondShareData = {
    body?: never;
    path: {
        /**
         * Share Sqid
         */
        share_sqid: string;
    };
    query?: never;
    url: '/api/ponds/shares/{share_sqid}';
};

export type PondsApiDeletePondShareResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PondsApiGetPondShareData = {
    body?: never;
    path: {
        /**
         * Share Sqid
         */
        share_sqid: string;
    };
    query?: never;
    url: '/api/ponds/shares/{share_sqid}';
};

export type PondsApiGetPondShareResponses = {
    /**
     * OK
     */
    200: PondShareSchema;
};

export type PondsApiGetPondShareResponse = PondsApiGetPondShareResponses[keyof PondsApiGetPondShareResponses];

export type PondsApiGetPublicPondData = {
    body?: never;
    path: {
        /**
         * Share Sqid
         */
        share_sqid: string;
    };
    query?: never;
    url: '/api/ponds/public/{share_sqid}';
};

export type PondsApiGetPublicPondResponses = {
    /**
     * OK
     */
    200: PublicPondSchema;
};

export type PondsApiGetPublicPondResponse = PondsApiGetPublicPondResponses[keyof PondsApiGetPublicPondResponses];

export type DocumentsApiListDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Processing Status
         */
        processing_status?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/documents/';
};

export type DocumentsApiListDocumentsResponses = {
    /**
     * OK
     */
    200: PagedDocumentSchema;
};

export type DocumentsApiListDocumentsResponse = DocumentsApiListDocumentsResponses[keyof DocumentsApiListDocumentsResponses];

export type DocumentsApiCreateDocumentData = {
    body: DocumentCreateSchema;
    path?: never;
    query?: never;
    url: '/api/documents/';
};

export type DocumentsApiCreateDocumentResponses = {
    /**
     * OK
     */
    200: DocumentSchema;
};

export type DocumentsApiCreateDocumentResponse = DocumentsApiCreateDocumentResponses[keyof DocumentsApiCreateDocumentResponses];

export type DocumentsApiUploadDocumentData = {
    /**
     * MultiPartBodyParams
     */
    body: {
        /**
         * File
         */
        file: Blob | File;
        /**
         * Title
         */
        title: string;
        /**
         * Pond Sqid
         */
        pond_sqid: string;
        /**
         * Docling Preset Sqid
         */
        docling_preset_sqid?: string;
        /**
         * Ocr Preset Sqid
         */
        ocr_preset_sqid?: string;
        /**
         * Metadata
         */
        metadata?: string;
    };
    path?: never;
    query?: never;
    url: '/api/documents/upload/';
};

export type DocumentsApiUploadDocumentResponses = {
    /**
     * OK
     */
    200: DocumentSchema;
};

export type DocumentsApiUploadDocumentResponse = DocumentsApiUploadDocumentResponses[keyof DocumentsApiUploadDocumentResponses];

export type DocumentsApiDeleteDocumentData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/documents/{sqid}';
};

export type DocumentsApiDeleteDocumentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DocumentsApiGetDocumentData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/documents/{sqid}';
};

export type DocumentsApiGetDocumentResponses = {
    /**
     * OK
     */
    200: DocumentSchema;
};

export type DocumentsApiGetDocumentResponse = DocumentsApiGetDocumentResponses[keyof DocumentsApiGetDocumentResponses];

export type DocumentsApiUpdateDocumentData = {
    body: DocumentUpdateSchema;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/documents/{sqid}';
};

export type DocumentsApiUpdateDocumentResponses = {
    /**
     * OK
     */
    200: DocumentSchema;
};

export type DocumentsApiUpdateDocumentResponse = DocumentsApiUpdateDocumentResponses[keyof DocumentsApiUpdateDocumentResponses];

export type DocumentsApiGetDocumentProgressData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/documents/{sqid}/progress';
};

export type DocumentsApiGetDocumentProgressResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DocumentsApiListPagesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Document Id
         */
        document_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/pages/';
};

export type DocumentsApiListPagesResponses = {
    /**
     * OK
     */
    200: PagedPageSchema;
};

export type DocumentsApiListPagesResponse = DocumentsApiListPagesResponses[keyof DocumentsApiListPagesResponses];

export type DocumentsApiGetPageData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/pages/{sqid}';
};

export type DocumentsApiGetPageResponses = {
    /**
     * OK
     */
    200: PageDetailsSchema;
};

export type DocumentsApiGetPageResponse = DocumentsApiGetPageResponses[keyof DocumentsApiGetPageResponses];

export type DocumentsApiUpdatePageData = {
    body: PageUpdateSchema;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/pages/{sqid}';
};

export type DocumentsApiUpdatePageResponses = {
    /**
     * OK
     */
    200: PageSchema;
};

export type DocumentsApiUpdatePageResponse = DocumentsApiUpdatePageResponses[keyof DocumentsApiUpdatePageResponses];

export type DocumentsApiGetPageImagesData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/pages/{sqid}/images/';
};

export type DocumentsApiGetPageImagesResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<ImageSchema>;
};

export type DocumentsApiGetPageImagesResponse = DocumentsApiGetPageImagesResponses[keyof DocumentsApiGetPageImagesResponses];

export type DocumentsApiReprocessPageData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/pages/{sqid}/reprocess';
};

export type DocumentsApiReprocessPageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DocumentsApiGetImageData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/images/{sqid}';
};

export type DocumentsApiGetImageResponses = {
    /**
     * OK
     */
    200: ImageSchema;
};

export type DocumentsApiGetImageResponse = DocumentsApiGetImageResponses[keyof DocumentsApiGetImageResponses];

export type DocumentsApiSearchPagesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Min Score
         */
        min_score?: number | null;
        /**
         * Document Title
         */
        document_title?: string | null;
        /**
         * Pond Name
         */
        pond_name?: string | null;
    };
    url: '/api/search/';
};

export type DocumentsApiSearchPagesResponses = {
    /**
     * OK
     */
    200: SearchResultSchema;
};

export type DocumentsApiSearchPagesResponse = DocumentsApiSearchPagesResponses[keyof DocumentsApiSearchPagesResponses];

export type OcrPresetsApiListOcrPresetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ocr-presets/';
};

export type OcrPresetsApiListOcrPresetsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<OcrPresetSchema>;
};

export type OcrPresetsApiListOcrPresetsResponse = OcrPresetsApiListOcrPresetsResponses[keyof OcrPresetsApiListOcrPresetsResponses];

export type OcrPresetsApiCreateOcrPresetData = {
    body: OcrPresetCreateSchema;
    path?: never;
    query?: never;
    url: '/api/ocr-presets/';
};

export type OcrPresetsApiCreateOcrPresetResponses = {
    /**
     * OK
     */
    200: OcrPresetSchema;
};

export type OcrPresetsApiCreateOcrPresetResponse = OcrPresetsApiCreateOcrPresetResponses[keyof OcrPresetsApiCreateOcrPresetResponses];

export type OcrPresetsApiDeleteOcrPresetData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/ocr-presets/{sqid}';
};

export type OcrPresetsApiDeleteOcrPresetResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type OcrPresetsApiGetOcrPresetData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/ocr-presets/{sqid}';
};

export type OcrPresetsApiGetOcrPresetResponses = {
    /**
     * OK
     */
    200: OcrPresetSchema;
};

export type OcrPresetsApiGetOcrPresetResponse = OcrPresetsApiGetOcrPresetResponses[keyof OcrPresetsApiGetOcrPresetResponses];

export type OcrPresetsApiUpdateOcrPresetData = {
    body: OcrPresetUpdateSchema;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/ocr-presets/{sqid}';
};

export type OcrPresetsApiUpdateOcrPresetResponses = {
    /**
     * OK
     */
    200: OcrPresetSchema;
};

export type OcrPresetsApiUpdateOcrPresetResponse = OcrPresetsApiUpdateOcrPresetResponses[keyof OcrPresetsApiUpdateOcrPresetResponses];

export type OcrPresetsApiGetDefaultPresetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ocr-presets/default/get';
};

export type OcrPresetsApiGetDefaultPresetResponses = {
    /**
     * OK
     */
    200: OcrPresetSchema;
};

export type OcrPresetsApiGetDefaultPresetResponse = OcrPresetsApiGetDefaultPresetResponses[keyof OcrPresetsApiGetDefaultPresetResponses];

export type DoclingPresetsApiListDoclingPresetsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/docling-presets/';
};

export type DoclingPresetsApiListDoclingPresetsResponses = {
    /**
     * OK
     */
    200: PagedDoclingPresetSchema;
};

export type DoclingPresetsApiListDoclingPresetsResponse = DoclingPresetsApiListDoclingPresetsResponses[keyof DoclingPresetsApiListDoclingPresetsResponses];

export type DoclingPresetsApiCreateDoclingPresetData = {
    body: DoclingPresetCreateSchema;
    path?: never;
    query?: never;
    url: '/api/docling-presets/';
};

export type DoclingPresetsApiCreateDoclingPresetResponses = {
    /**
     * OK
     */
    200: DoclingPresetSchema;
};

export type DoclingPresetsApiCreateDoclingPresetResponse = DoclingPresetsApiCreateDoclingPresetResponses[keyof DoclingPresetsApiCreateDoclingPresetResponses];

export type DoclingPresetsApiDeleteDoclingPresetData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/docling-presets/{sqid}';
};

export type DoclingPresetsApiDeleteDoclingPresetResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DoclingPresetsApiGetDoclingPresetData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/docling-presets/{sqid}';
};

export type DoclingPresetsApiGetDoclingPresetResponses = {
    /**
     * OK
     */
    200: DoclingPresetSchema;
};

export type DoclingPresetsApiGetDoclingPresetResponse = DoclingPresetsApiGetDoclingPresetResponses[keyof DoclingPresetsApiGetDoclingPresetResponses];

export type DoclingPresetsApiUpdateDoclingPresetData = {
    body: DoclingPresetUpdateSchema;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/docling-presets/{sqid}';
};

export type DoclingPresetsApiUpdateDoclingPresetResponses = {
    /**
     * OK
     */
    200: DoclingPresetSchema;
};

export type DoclingPresetsApiUpdateDoclingPresetResponse = DoclingPresetsApiUpdateDoclingPresetResponses[keyof DoclingPresetsApiUpdateDoclingPresetResponses];

export type DoclingPresetsApiSetDefaultDoclingPresetData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/docling-presets/{sqid}/set-default';
};

export type DoclingPresetsApiSetDefaultDoclingPresetResponses = {
    /**
     * OK
     */
    200: DoclingPresetSchema;
};

export type DoclingPresetsApiSetDefaultDoclingPresetResponse = DoclingPresetsApiSetDefaultDoclingPresetResponses[keyof DoclingPresetsApiSetDefaultDoclingPresetResponses];

export type DoclingPresetsApiGetDefaultDoclingPresetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/docling-presets/default/get';
};

export type DoclingPresetsApiGetDefaultDoclingPresetResponses = {
    /**
     * OK
     */
    200: DoclingPresetSchema;
};

export type DoclingPresetsApiGetDefaultDoclingPresetResponse = DoclingPresetsApiGetDefaultDoclingPresetResponses[keyof DoclingPresetsApiGetDefaultDoclingPresetResponses];
