// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * BucketSchema
 */
export type BucketSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * BucketCreateSchema
 */
export type BucketCreateSchema = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * BucketUpdateSchema
 */
export type BucketUpdateSchema = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * DocumentListFilterSchema
 */
export type DocumentListFilterSchema = {
    /**
     * Processing Status
     */
    processing_status?: string | null;
};

/**
 * Input
 */
export type Input = {
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
};

/**
 * DocumentSchema
 */
export type DocumentSchema = {
    /**
     * Processing Progress
     */
    processing_progress: number;
    /**
     * Pages
     */
    pages: Array<PageSchema>;
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Title
     */
    title: string;
    /**
     * Thumbnail
     */
    thumbnail?: string | null;
    /**
     * Page Count
     */
    page_count?: number;
    /**
     * Original Pdf
     */
    original_pdf: string;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PageSchema
 */
export type PageSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Page Number
     */
    page_number: number;
};

/**
 * PagedDocumentSchema
 */
export type PagedDocumentSchema = {
    /**
     * Items
     */
    items: Array<DocumentSchema>;
    /**
     * Count
     */
    count: number;
};

/**
 * DocumentCreateSchema
 */
export type DocumentCreateSchema = {
    /**
     * Title
     */
    title: string;
    /**
     * Group Sqid
     */
    group_sqid: string;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * DocumentUpdateSchema
 */
export type DocumentUpdateSchema = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * PagesListFilterSchema
 */
export type PagesListFilterSchema = {
    /**
     * Document Id
     */
    document_id?: string | null;
};

/**
 * PageSchema2
 */
export type PageSchema2 = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Page Number
     */
    page_number: number;
    /**
     * Page Pdf
     */
    page_pdf: string;
    /**
     * Ocr Markdown Raw
     */
    ocr_markdown_raw?: string | null;
    /**
     * Text Markdown Clean
     */
    text_markdown_clean?: string | null;
    /**
     * Processing Status
     */
    processing_status?: string;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PagedPageSchema2
 */
export type PagedPageSchema2 = {
    /**
     * Items
     */
    items: Array<PageSchema2>;
    /**
     * Count
     */
    count: number;
};

/**
 * PageUpdateSchema
 */
export type PageUpdateSchema = {
    /**
     * Ocr Markdown Raw
     */
    ocr_markdown_raw?: string | null;
    /**
     * Text Markdown Clean
     */
    text_markdown_clean?: string | null;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ImageSchema
 */
export type ImageSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Image File
     */
    image_file: string;
    /**
     * Caption
     */
    caption?: string | null;
    /**
     * Metadata
     */
    metadata: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * SearchResultSchema
 */
export type SearchResultSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Document Title
     */
    document_title: string;
    /**
     * Document Sqid
     */
    document_sqid: string;
    /**
     * Bucket Name
     */
    bucket_name: string;
    /**
     * Bucket Sqid
     */
    bucket_sqid: string;
    /**
     * Page Number
     */
    page_number: number;
    /**
     * Snippet
     */
    snippet: string;
    /**
     * Relevance Score
     */
    relevance_score?: number | null;
};

/**
 * SearchQuerySchema
 */
export type SearchQuerySchema = {
    /**
     * Q
     */
    q: string;
    /**
     * Bucket Sqid
     */
    bucket_sqid?: string | null;
    /**
     * Document Sqid
     */
    document_sqid?: string | null;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
};

/**
 * DoclingSettingsSchema
 */
export type DoclingSettingsSchema = {
    /**
     * Sqid
     */
    sqid: string;
    /**
     * Name
     */
    name: string;
    /**
     * Ocr Engine
     */
    ocr_engine: string;
    /**
     * Detect Tables
     */
    detect_tables: boolean;
    /**
     * Detect Figures
     */
    detect_figures: boolean;
    /**
     * Ignore Headers Footers
     */
    ignore_headers_footers: boolean;
    /**
     * Language
     */
    language: string;
    /**
     * Confidence Threshold
     */
    confidence_threshold: number;
    /**
     * Settings Json
     */
    settings_json: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DoclingSettingsUpdateSchema
 */
export type DoclingSettingsUpdateSchema = {
    /**
     * Ocr Engine
     */
    ocr_engine?: string | null;
    /**
     * Detect Tables
     */
    detect_tables?: boolean | null;
    /**
     * Detect Figures
     */
    detect_figures?: boolean | null;
    /**
     * Ignore Headers Footers
     */
    ignore_headers_footers?: boolean | null;
    /**
     * Language
     */
    language?: string | null;
    /**
     * Confidence Threshold
     */
    confidence_threshold?: number | null;
    /**
     * Settings Json
     */
    settings_json?: {
        [key: string]: unknown;
    } | null;
};

export type PagewiseApiHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type PagewiseApiHealthCheckResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type BucketApiListBucketsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/buckets/';
};

export type BucketApiListBucketsResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<BucketSchema>;
};

export type BucketApiListBucketsResponse = BucketApiListBucketsResponses[keyof BucketApiListBucketsResponses];

export type BucketApiCreateBucketData = {
    body: BucketCreateSchema;
    path?: never;
    query?: never;
    url: '/api/buckets/';
};

export type BucketApiCreateBucketResponses = {
    /**
     * OK
     */
    200: BucketSchema;
};

export type BucketApiCreateBucketResponse = BucketApiCreateBucketResponses[keyof BucketApiCreateBucketResponses];

export type BucketApiDeleteBucketData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/buckets/{sqid}';
};

export type BucketApiDeleteBucketResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type BucketApiGetBucketData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/buckets/{sqid}';
};

export type BucketApiGetBucketResponses = {
    /**
     * OK
     */
    200: BucketSchema;
};

export type BucketApiGetBucketResponse = BucketApiGetBucketResponses[keyof BucketApiGetBucketResponses];

export type BucketApiUpdateBucketData = {
    body: BucketUpdateSchema;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/buckets/{sqid}';
};

export type BucketApiUpdateBucketResponses = {
    /**
     * OK
     */
    200: BucketSchema;
};

export type BucketApiUpdateBucketResponse = BucketApiUpdateBucketResponses[keyof BucketApiUpdateBucketResponses];

export type DocumentsApiListDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Processing Status
         */
        processing_status?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/documents/';
};

export type DocumentsApiListDocumentsResponses = {
    /**
     * OK
     */
    200: PagedDocumentSchema;
};

export type DocumentsApiListDocumentsResponse = DocumentsApiListDocumentsResponses[keyof DocumentsApiListDocumentsResponses];

export type DocumentsApiCreateDocumentData = {
    body: DocumentCreateSchema;
    path?: never;
    query?: never;
    url: '/api/documents/';
};

export type DocumentsApiCreateDocumentResponses = {
    /**
     * OK
     */
    200: DocumentSchema;
};

export type DocumentsApiCreateDocumentResponse = DocumentsApiCreateDocumentResponses[keyof DocumentsApiCreateDocumentResponses];

export type DocumentsApiUploadDocumentData = {
    /**
     * MultiPartBodyParams
     */
    body: {
        /**
         * File
         */
        file: Blob | File;
        /**
         * Title
         */
        title: string;
        /**
         * Group Sqid
         */
        group_sqid: string;
        /**
         * Metadata
         */
        metadata?: string;
    };
    path?: never;
    query?: never;
    url: '/api/documents/upload/';
};

export type DocumentsApiUploadDocumentResponses = {
    /**
     * OK
     */
    200: DocumentSchema;
};

export type DocumentsApiUploadDocumentResponse = DocumentsApiUploadDocumentResponses[keyof DocumentsApiUploadDocumentResponses];

export type DocumentsApiDeleteDocumentData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/documents/{sqid}';
};

export type DocumentsApiDeleteDocumentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DocumentsApiGetDocumentData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/documents/{sqid}';
};

export type DocumentsApiGetDocumentResponses = {
    /**
     * OK
     */
    200: DocumentSchema;
};

export type DocumentsApiGetDocumentResponse = DocumentsApiGetDocumentResponses[keyof DocumentsApiGetDocumentResponses];

export type DocumentsApiUpdateDocumentData = {
    body: DocumentUpdateSchema;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/documents/{sqid}';
};

export type DocumentsApiUpdateDocumentResponses = {
    /**
     * OK
     */
    200: DocumentSchema;
};

export type DocumentsApiUpdateDocumentResponse = DocumentsApiUpdateDocumentResponses[keyof DocumentsApiUpdateDocumentResponses];

export type DocumentsApiGetDocumentProgressData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/documents/{sqid}/progress';
};

export type DocumentsApiGetDocumentProgressResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DocumentsApiListPagesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Document Id
         */
        document_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/pages/';
};

export type DocumentsApiListPagesResponses = {
    /**
     * OK
     */
    200: PagedPageSchema2;
};

export type DocumentsApiListPagesResponse = DocumentsApiListPagesResponses[keyof DocumentsApiListPagesResponses];

export type DocumentsApiGetPageData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/pages/{sqid}';
};

export type DocumentsApiGetPageResponses = {
    /**
     * OK
     */
    200: PageSchema2;
};

export type DocumentsApiGetPageResponse = DocumentsApiGetPageResponses[keyof DocumentsApiGetPageResponses];

export type DocumentsApiUpdatePageData = {
    body: PageUpdateSchema;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/pages/{sqid}';
};

export type DocumentsApiUpdatePageResponses = {
    /**
     * OK
     */
    200: PageSchema2;
};

export type DocumentsApiUpdatePageResponse = DocumentsApiUpdatePageResponses[keyof DocumentsApiUpdatePageResponses];

export type DocumentsApiGetPageImagesData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/pages/{sqid}/images/';
};

export type DocumentsApiGetPageImagesResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<ImageSchema>;
};

export type DocumentsApiGetPageImagesResponse = DocumentsApiGetPageImagesResponses[keyof DocumentsApiGetPageImagesResponses];

export type DocumentsApiGetImageData = {
    body?: never;
    path: {
        /**
         * Sqid
         */
        sqid: string;
    };
    query?: never;
    url: '/api/images/{sqid}';
};

export type DocumentsApiGetImageResponses = {
    /**
     * OK
     */
    200: ImageSchema;
};

export type DocumentsApiGetImageResponse = DocumentsApiGetImageResponses[keyof DocumentsApiGetImageResponses];

export type DocumentsApiSearchPagesData = {
    body: SearchQuerySchema;
    path?: never;
    query?: never;
    url: '/api/search/';
};

export type DocumentsApiSearchPagesResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<SearchResultSchema>;
};

export type DocumentsApiSearchPagesResponse = DocumentsApiSearchPagesResponses[keyof DocumentsApiSearchPagesResponses];

export type DocumentsApiGetDoclingSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/';
};

export type DocumentsApiGetDoclingSettingsResponses = {
    /**
     * OK
     */
    200: DoclingSettingsSchema;
};

export type DocumentsApiGetDoclingSettingsResponse = DocumentsApiGetDoclingSettingsResponses[keyof DocumentsApiGetDoclingSettingsResponses];

export type DocumentsApiUpdateDoclingSettingsData = {
    body: DoclingSettingsUpdateSchema;
    path?: never;
    query?: never;
    url: '/api/settings/';
};

export type DocumentsApiUpdateDoclingSettingsResponses = {
    /**
     * OK
     */
    200: DoclingSettingsSchema;
};

export type DocumentsApiUpdateDoclingSettingsResponse = DocumentsApiUpdateDoclingSettingsResponses[keyof DocumentsApiUpdateDoclingSettingsResponses];
